using LostAndFound.PublicationService.ThirdPartyServices.Extensions;

namespace LostAndFound.PublicationService.ThirdPartyServices.Models
{
    public class FileDto
    {
        public Stream Content { get; set; } = Stream.Null;
        public string Name { get; set; } = string.Empty;
        public string ContentType { get; set; } = string.Empty;


        public string GetPathWithFileName()
        {
            var uniqueAutoGeneratedFileName = Path.GetRandomFileName();
            var shorterClientSideFileName = Path.GetFileNameWithoutExtension(Name)
                .TruncateToShortString(10);
            var extension = Path.GetExtension(Name);

            return $"{uniqueAutoGeneratedFileName}_{shorterClientSideFileName}{extension}";
        }
    }
}
