name: $(date:yyyyMMdd)$(rev:.r)_$(SourceBranchName)-$(BuildId)-PublicationServiceWebApiBuildWithTests

pool: Default

trigger:
  paths:
    include:
    - Backend/PublicationService/*

stages:
  - template: Templates/build-with-tests-webapi-template.yml
    parameters:
      webapiProjectDirectory: Backend/PublicationService/src/LostAndFound.PublicationService
      unitTestProjectDirectory: Backend/PublicationService/tests/LostAndFound.PublicationService.UnitTests
      runUnitTests: true
      integrationTestProjectDirectory: Backend/PublicationService/tests/LostAndFound.PublicationService.IntegrationTests
      runIntegrationTests: true
      artifactName: LostAndFound.PublicationService