name: $(date:yyyyMMdd)$(rev:.r)_$(SourceBranchName)-$(BuildId)-AuthServiceWebApiBuildWithTests

pool: Default

trigger:
  paths:
    include:
    - Backend/AuthService/*

stages:
  - template: Templates/build-with-tests-webapi-template.yml
    parameters:
      webapiProjectDirectory: Backend/AuthService/src/LostAndFound.AuthService
      unitTestProjectDirectory: Backend/AuthService/tests/LostAndFound.AuthService.UnitTests
      runUnitTests: true
      integrationTestProjectDirectory: Backend/AuthService/tests/LostAndFound.AuthService.IntegrationTests
      runIntegrationTests: true
      artifactName: LostAndFound.AuthService