name: $(date:yyyyMMdd)$(rev:.r)_$(SourceBranchName)-$(BuildId)-ProfileServiceWebApiBuildWithTests

pool: Default

trigger:
  paths:
    include:
    - Backend/ProfileService/*

stages:
  - template: Templates/build-with-tests-webapi-template.yml
    parameters:
      webapiProjectDirectory: Backend/ProfileService/src/LostAndFound.ProfileService
      unitTestProjectDirectory: Backend/ProfileService/tests/LostAndFound.ProfileService.UnitTests
      runUnitTests: true
      integrationTestProjectDirectory: Backend/ProfileService/tests/LostAndFound.ProfileService.IntegrationTests
      runIntegrationTests: true
      artifactName: LostAndFound.ProfileService